[lib]
crate-type = ["staticlib"]

[package]
name = "spotiqueue-worker"
version = "0.1.0"
authors = ["paul <423357+toothbrush@users.noreply.github.com>"]
edition = "2018"

[build-dependencies]
cbindgen = "0.19.0"
