[lib]
crate-type = ["staticlib", "rlib"]

[profile.release]
debug = 1

[package]
name = "spotiqueue_worker"
version = "0.2.0"
authors = ["paul <423357+toothbrush@users.noreply.github.com>"]
edition = "2018"

[build-dependencies]
cbindgen = "0.20.0"

[dependencies]
env_logger = "0.9.0"
librespot = "0.3.1"
log = "0.4.14"
once_cell = "1.8.0"
tokio = "1.14.0"
